### ISSUE TITLE
error fetching the data 

### ISSUE THREAD

**Issue by tilakpatel22** [addypy/datagovindia#8]
from datagovindia import DataGovIndia

def sync_data():
    # Specify API key
    datagovin = DataGovIndia(api_key='')
    search_data = datagovin.search('mgnrega', search_fields=['title', 'description'])
    data = datagovin.get_resource_info(resource_id='t_0c892b6a_3951_419d_b812_0a4b4a066e94')
    print(search_data.to_csv('new.csv'))

if __name__ == '__main__':
    sync_data() 

OUTPUT:
Fetching info for resource_id 't_0c892b6a_3951_419d_b812_0a4b4a066e94'...
Traceback (most recent call last):
  File "C:\Users\Tilak\django-dashboard-app\dirr\fetched.py", line 62, in <module>
    cli()
  File "C:\python11\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tilak\django-dashboard-app\dirr\fetched.py", line 48, in get_resource_info_cli
    info = datagovin.get_resource_info(resource_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\datagovindia\__init__.py", line 462, in get_resource_info
    api_info = get_api_info(url)
               ^^^^^^^^^^^^^^^^^
  File "C:\python11\Lib\site-packages\datagovindia\__init__.py", line 206, in get_api_info
    response[key] = True if response[key] == "1" else False
                            ~~~~~~~~^^^^^
KeyError: 'visualizable'

I'm facing this error on the latest version of this library can you please help me with it

**Comment by addypy** [comment]
Thank you for reporting the issue. The issue has been resolved in the latest release `v1.0.2`.

1. We removed the conditions that were halting the operation due to changes in the fields/keys from data.gov.in.
2. Integrated `Tenacity` to handle network errors with retries using exponential backoff.

Please update to the latest version by running:

```bash
pip install --upgrade datagovindia
```

You can verify the update using the CLI:

```bash
datagovindia version
```

Expected output:

```
datagovindia v1.0.2
```

or in python

```python
import datagovindia
print(datagovindia.__version__)
```

Expected output:

```
1.0.2
```

Let us know if you encounter any further issues!
